<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INV-CR-000905</name>
   <tag></tag>
   <elementGuidId>7810f6de-3d02-4b1c-ad74-877849872c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td:nth-of-type(2) > a.no_reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;INV-CR-000905&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cf632b2-f0a7-4910-b307-0d3f333bfa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_reference</value>
      <webElementGuid>eab63c1c-3177-4e83-9504-15bb86aed5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/241?from=my_approval</value>
      <webElementGuid>fdbcc678-20ef-4a5b-9cfa-43dce97888d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INV-CR-000905</value>
      <webElementGuid>2b505f95-73dd-4411-80a4-9e0979706863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approvals&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[2]/a[@class=&quot;no_reference&quot;]</value>
      <webElementGuid>3909197c-b9a2-4838-bc66-645ca8c881b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>40a73fd3-ac40-4caa-9c86-dcdc37720d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INV-CR-000905')]</value>
      <webElementGuid>f4ee1b0f-6e0d-4981-91ed-37eb99e62bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::a[1]</value>
      <webElementGuid>95f90832-4cb5-4d21-85f1-9c165f4493ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[1]/following::a[1]</value>
      <webElementGuid>2746ab11-3438-4e12-a62f-af8edf50cc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Integra Solusi Mandiri _CR 6'])[1]/preceding::a[1]</value>
      <webElementGuid>8d968cd2-d7f1-407d-aad8-bd7984b76028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[2]/preceding::a[1]</value>
      <webElementGuid>44eed03e-9fa0-4caa-b338-bd0b9c473133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INV-CR-000905']/parent::*</value>
      <webElementGuid>440f72b3-8be2-4f3f-93db-018a26788cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/241?from=my_approval')]</value>
      <webElementGuid>0c0780d2-9524-4db6-9bf9-ac199a423568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>9f061948-86ad-4cce-a582-e276e384b9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/241?from=my_approval' and (text() = 'INV-CR-000905' or . = 'INV-CR-000905')]</value>
      <webElementGuid>6171c147-4fe5-4eb7-83dc-16db1da9a4fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
