<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INV-OnTopList</name>
   <tag></tag>
   <elementGuidId>8aacf6dd-44f8-4568-94c0-bf68b2ef71fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.no_reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_approvals']/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;INV-REGRESXXX-007782&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1018642-8a63-4142-813b-7562b3e46f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_reference</value>
      <webElementGuid>527c0c33-6c5b-4f8d-9e92-394fd534af44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/223?from=my_approval</value>
      <webElementGuid>e82f068b-021d-4c3d-9469-d49f75b53082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INV-REGRESXXX-007782</value>
      <webElementGuid>cd735bc2-f45b-4162-9790-bbce990b7a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approvals&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[@class=&quot;no_reference&quot;]</value>
      <webElementGuid>3a89e3ee-4998-467a-9464-a65aed4101de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approvals']/tbody/tr/td[2]/a</value>
      <webElementGuid>b3f79a99-b75f-44ae-a0cf-1d894d9bb6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INV-REGRESXXX-007782')]</value>
      <webElementGuid>ccdae10d-c339-4694-aff5-0e7139f0506a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>814de7db-329e-48c9-b270-2fe899e8bf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::a[1]</value>
      <webElementGuid>30aa402c-8ec4-4a74-b46a-aae1772f9d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT.Teknologi Utama Jaya REGRES XXX'])[1]/preceding::a[1]</value>
      <webElementGuid>866ce255-8153-44ce-80b3-c4707d66a960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[1]/preceding::a[1]</value>
      <webElementGuid>e16a0188-b32d-4843-aeb6-699bbafbfc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INV-REGRESXXX-007782']/parent::*</value>
      <webElementGuid>d76570a7-c5fc-4cf2-9897-4dc96260e02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/223?from=my_approval')]</value>
      <webElementGuid>22b75301-8d29-465f-bcbc-310c34ecb3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>9ad873be-d7a2-4707-be4a-51e5bd257226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/223?from=my_approval' and (text() = 'INV-REGRESXXX-007782' or . = 'INV-REGRESXXX-007782')]</value>
      <webElementGuid>e92bc32e-6c95-44e5-9ad2-61a3c4a061a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
