<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_IN-0000004107_Draft-PIL</name>
   <tag></tag>
   <elementGuidId>e8d3e11e-438c-465c-a72e-306a07ff59f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='149']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.select-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;IN-0000004107 INV-009-PIL-TEST 26-06-2025 PT.Berdikari Maju iii 88.200.000,00   Draft  &quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27a3c4c2-e254-4f4c-b265-aaf3de416593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>45c36860-8835-4278-ba59-f160d2911b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-checkbox</value>
      <webElementGuid>eac3c7b2-7c42-4e66-8c1f-62428531a191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>149</value>
      <webElementGuid>53ef497e-3bc7-4417-a413-5058e58f69b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cansubmit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd98eb8f-18ff-4652-998f-5a4c8d1f04e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_draft_invoices&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center sorting_1&quot;]/input[@class=&quot;select-checkbox&quot;]</value>
      <webElementGuid>11c4e529-ab10-4f0f-bf76-8fecd20e758e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='149']</value>
      <webElementGuid>048b71d2-65c4-4d73-8c7f-40810fe0aebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_draft_invoices']/tbody/tr/td/input</value>
      <webElementGuid>63e66804-8f94-4d40-be09-41d2b4aa0055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a480be6e-15d2-4b2d-a9ee-5f0b50e0135e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>61bce922-e84f-42f9-9dae-7897cbe65107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
