<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_IN-0000004104_Draft-PIL</name>
   <tag></tag>
   <elementGuidId>5a8563bc-097c-469a-b5b3-89a22b9690bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='146']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.even > td.text-center.sorting_1 > input.select-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;IN-0000004104 INV-006-PIL-TEST 23-06-2025 PT.Teknologi Utama Jaya iii 58.800.000,00   Draft  &quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dd284c4-fbd4-4abd-82ad-b67440503aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8bee151b-5e01-4e2f-9e77-f39f7621fd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-checkbox</value>
      <webElementGuid>34a06f4e-146d-4589-b2a9-8fcb28644023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>146</value>
      <webElementGuid>45ef1d52-c684-446d-af13-af192af4f5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cansubmit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3a9a474-6d97-4082-b3cd-5d2fdd1199da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_draft_invoices&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;text-center sorting_1&quot;]/input[@class=&quot;select-checkbox&quot;]</value>
      <webElementGuid>57c099c6-9a38-40ec-b050-e052eadaa0df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='146']</value>
      <webElementGuid>e3dd1a94-b6c2-4002-9270-e3b1435db5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_draft_invoices']/tbody/tr[2]/td/input</value>
      <webElementGuid>4de6c7ab-54cd-4c57-938b-0d77fef3c6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>edd7fc6b-76c7-418b-89c5-10848a9b6e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>a56b591c-14ac-4d51-9c44-38047a5130d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
