<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_select-checkbox_PI.25.04.0037</name>
   <tag></tag>
   <elementGuidId>1d39311e-2c00-4b25-b119-de21e3063353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='79']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.select-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;PI.25.04.0037 2024/GCC/07/0210 08-04-2025 PT. Grand Cipta Cemerlang 1.000.000,00 Draft  &quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89792831-773f-4ef9-a821-011007fc0117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e7dad70f-2288-4cec-bdc5-31d991c840aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-checkbox</value>
      <webElementGuid>4383eb54-1c64-4d4e-bc55-dfe24a369945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>79</value>
      <webElementGuid>88466356-cf1c-4134-9a3a-32703b0694b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cansubmit</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46e42d23-4eb6-4a04-8803-ad1f886a1267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_draft_invoices&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center sorting_1&quot;]/input[@class=&quot;select-checkbox&quot;]</value>
      <webElementGuid>c276f092-a187-4772-982d-560725e7660b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='79']</value>
      <webElementGuid>bff820a8-4677-4bfa-ab67-5216e987ebb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_draft_invoices']/tbody/tr/td/input</value>
      <webElementGuid>65fccf05-efb5-4740-8144-98f07edbe6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>88c49a21-629e-40fa-9882-899bde09a0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>9ad5639c-6569-4c5e-89a5-190bef7cdb44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
