<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Update_add_delete</name>
   <tag></tag>
   <elementGuidId>c8f9f42a-12ca-46f6-a222-39fcd954d42e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add_delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Delete&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38840a81-d7c2-492f-b449-d08b69dffc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>81f2ac8d-3275-4b1e-8810-96848e0b0f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>64d19491-3900-4605-a3b0-c9dcb3dfd364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_delete</value>
      <webElementGuid>b228b601-28dc-40e7-b6ad-3718653b5f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>3269c3dd-6341-4ed2-b3bd-26a9bf591a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da2bf60c-b135-460d-bfcf-122db6c93ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_delete&quot;)</value>
      <webElementGuid>786aa7d3-b13a-46cd-a171-089873a8c015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add_delete']</value>
      <webElementGuid>0c07879e-1618-4734-be4b-a0177bd4f9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='assignAccessForm']/div/div[9]/div[4]/input</value>
      <webElementGuid>0fca182d-9aeb-47e3-8f7c-fb0a8f04ee5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[4]/input</value>
      <webElementGuid>987ae9ee-4fcc-47f6-9ac9-cec95f37322a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'add_delete' and @name = 'delete']</value>
      <webElementGuid>58f75e49-2c2b-4ca9-bb35-cae335156dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
