<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_Assign-User</name>
   <tag></tag>
   <elementGuidId>c96da9fb-711c-4666-af1e-f1232626f8b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-user_assigned-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-user_assigned-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Firman Sahlani (firman.sahlani@mmsgroup.co.id)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>722d2784-de9f-4916-8cfa-b656842fd348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>966ece1a-fae8-4712-b616-86921686f310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-user_assigned-container</value>
      <webElementGuid>78bc46a2-3bfc-43f3-af3b-feb4b364d042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>de342a62-66c9-4c7e-b751-6eb2cb0493a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8b5a1bd6-ac9e-4024-96b0-0e7397af1c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Firman Sahlani (firman.sahlani@mmsgroup.co.id)</value>
      <webElementGuid>a06d2257-1f68-4639-a0d6-16216de113ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Firman Sahlani (firman.sahlani@mmsgroup.co.id)</value>
      <webElementGuid>a902705b-3503-46e3-8a68-aa3ca3d01ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-user_assigned-container&quot;)</value>
      <webElementGuid>4ef050db-e824-449c-9c98-9041b677c25c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-user_assigned-container']</value>
      <webElementGuid>c8a8d2b3-7875-4bc0-a391-8e7624378298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='assignUserForm']/div/div/div/div/span/span/span/span</value>
      <webElementGuid>028948c4-1012-4b7b-ac5f-9bd82d2c5bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User'])[1]/following::span[4]</value>
      <webElementGuid>84f7c16a-db89-424b-8abb-d4fbfb7e58df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign User'])[1]/following::span[4]</value>
      <webElementGuid>a2d2b324-5d45-46fe-94f3-6af1a51a19be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[4]</value>
      <webElementGuid>08140fab-724d-463a-971d-1beaae6e846a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>426b6dc4-df59-4574-a407-ff78e5e3b308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-user_assigned-container' and @title = 'Firman Sahlani (firman.sahlani@mmsgroup.co.id)' and (text() = '×Firman Sahlani (firman.sahlani@mmsgroup.co.id)' or . = '×Firman Sahlani (firman.sahlani@mmsgroup.co.id)')]</value>
      <webElementGuid>f7630a10-3e8d-4e57-8afe-1513ee124ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
