<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INV-CR-000901</name>
   <tag></tag>
   <elementGuidId>7dd89fce-47d4-4d1e-b096-08bf42c2960f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td:nth-of-type(2) > a.no_reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;INV-CR-000901&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03c24467-13f1-40b2-a461-f9b58f9254c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_reference</value>
      <webElementGuid>b54e7b59-fb30-47e2-b8e1-a37ec424f9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/237?from=my_approval</value>
      <webElementGuid>a0b4c1a4-4c93-4ff1-9a25-c36f342edae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INV-CR-000901</value>
      <webElementGuid>ad154478-2d70-4f31-a410-0a8cada56d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approvals&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[2]/a[@class=&quot;no_reference&quot;]</value>
      <webElementGuid>ef687812-6dd4-4e80-be0f-74da24f3a041</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>ee45017a-a73e-4c7f-9434-4f42988f4fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INV-CR-000901')]</value>
      <webElementGuid>36281f3e-d104-4ada-9566-2a86b6f20343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::a[1]</value>
      <webElementGuid>95e7315b-ad05-42dd-9809-923584d34b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[1]/following::a[1]</value>
      <webElementGuid>3b2c9431-ef2a-4acb-9ab4-d9d93a68f3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Integra Solusi Mandiri _CR 2'])[1]/preceding::a[1]</value>
      <webElementGuid>0b4d82ca-c9dc-4cc8-973a-e1bf44adedd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[2]/preceding::a[1]</value>
      <webElementGuid>12c2aec5-7e09-48ef-b4d2-b825f9ab7e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INV-CR-000901']/parent::*</value>
      <webElementGuid>28f8386a-9c24-4d2b-bd62-60da278c5e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/237?from=my_approval')]</value>
      <webElementGuid>28e89e7e-92c3-43f9-9ab8-48e75f5a2e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>ff4a7731-9fea-471c-9cc6-2d6b5f9acbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/237?from=my_approval' and (text() = 'INV-CR-000901' or . = 'INV-CR-000901')]</value>
      <webElementGuid>2cfcd5d7-a84d-4d0b-b570-f0c1f1b5aba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
