<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INV-CR-000905</name>
   <tag></tag>
   <elementGuidId>466ce1c9-80a7-40c9-aedc-7f22f07c57ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td:nth-of-type(2) > a.no_reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;INV-CR-000905&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f3dca25-3d94-4418-b16e-cfa172297b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_reference</value>
      <webElementGuid>35d0a96f-bc11-49af-8f70-3cd530d00957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/241?from=my_approval</value>
      <webElementGuid>e279b681-7246-41b2-8276-79653f444079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INV-CR-000905</value>
      <webElementGuid>111aeb8a-0581-4a4e-b13f-84fe4a0ce303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approvals&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[2]/a[@class=&quot;no_reference&quot;]</value>
      <webElementGuid>82bc41bb-3323-4b37-85d4-b7ffea682e6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>e78eef0b-3d7d-416e-a54f-09edd4ced4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INV-CR-000905')]</value>
      <webElementGuid>e20548e7-9ea0-433a-a6bc-ba0d3f95823d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::a[1]</value>
      <webElementGuid>8a046afa-4d6e-4314-9dd6-09f564a8e035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[1]/following::a[1]</value>
      <webElementGuid>978c05cc-0855-4d4d-b2ea-5c32ad95a184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Integra Solusi Mandiri _CR 6'])[1]/preceding::a[1]</value>
      <webElementGuid>550616d6-ed12-4fcb-8a7b-ba2fbef55b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[2]/preceding::a[1]</value>
      <webElementGuid>33d7c3c3-b882-41fa-bdf5-d9f0feeab010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INV-CR-000905']/parent::*</value>
      <webElementGuid>c71c10f4-439e-439b-bac5-1eaefd39ef84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/241?from=my_approval')]</value>
      <webElementGuid>fc6e9787-6fab-4a5e-b185-1636439c036e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>00585058-ce50-41d2-952b-effed213414e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/241?from=my_approval' and (text() = 'INV-CR-000905' or . = 'INV-CR-000905')]</value>
      <webElementGuid>01039069-817a-48b3-89e3-8bf82a8ae2a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
