<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code_EditDocumentType</name>
   <tag></tag>
   <elementGuidId>a749d5fc-9458-47d1-b8b4-ee44cc04f289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit_code</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2eff4b07-c931-4aad-b4f8-932133d1e5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afc619e7-78dd-461c-88ca-78f25358cedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2f3af4af-8ee7-4b62-9ccc-25a3edea15ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>2b0fa893-47b0-48c1-b559-34bc63a3c0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_code</value>
      <webElementGuid>12f9b4f2-db8c-4648-a846-c04e5868ccb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_code&quot;)</value>
      <webElementGuid>fb999463-664f-4c95-af66-0c438df226c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit_code']</value>
      <webElementGuid>36ec03a9-a89b-445d-a232-44ed7c7bec42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditDocumentType']/div[2]/div/input</value>
      <webElementGuid>4321b23a-65f1-4478-a377-1d44c602d1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/div[2]/div/input</value>
      <webElementGuid>437e01b9-0ea2-48c9-b980-6a15b89b84ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code' and @id = 'edit_code']</value>
      <webElementGuid>a2856724-ed3d-4046-bab7-0bc96cfbd9e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
