<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Edit_Status_EditDocumentType</name>
   <tag></tag>
   <elementGuidId>66b7cfe6-7480-4839-9d25-525f77c5cb89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='edit_status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit_status</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e55367e-5a63-4209-ad8d-30a677288879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>209cfe59-6e25-423a-b60c-b3f78a0afb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>44b7bfae-b39e-454f-9d7a-eda76d2dccad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_status</value>
      <webElementGuid>0ed68ec3-404b-4e01-9c7d-b4192dfa23df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Active
                  Inactive
              </value>
      <webElementGuid>ef544cfc-e722-4eda-af03-b9d46b035232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_status&quot;)</value>
      <webElementGuid>5a6435fd-48de-4149-a8ef-7eb3fe0d013e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edit_status']</value>
      <webElementGuid>a38cfd78-8b17-4750-91f0-d4ad2fec521b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditDocumentType']/div[2]/div[4]/select</value>
      <webElementGuid>54b006f0-0fcb-437f-a98c-f92241d353e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::select[1]</value>
      <webElementGuid>fe21fab4-fbf9-434f-b5af-d53088406e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::select[1]</value>
      <webElementGuid>d8e6510b-478b-474f-86ca-72c7d6551887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::select[1]</value>
      <webElementGuid>49a32dbe-f788-4c95-9b96-261f1e4402d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::select[1]</value>
      <webElementGuid>6ec9fe9a-a8e2-4645-ae92-580acea4361d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/div[2]/div[4]/select</value>
      <webElementGuid>78a6901f-03bb-4406-827d-331d7fdece6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status' and @id = 'edit_status' and (text() = '
                  Active
                  Inactive
              ' or . = '
                  Active
                  Inactive
              ')]</value>
      <webElementGuid>0fb26eb9-3168-4f29-b04a-da16e1d52172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
