<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_EditDocumentType</name>
   <tag></tag>
   <elementGuidId>0c91bd81-d748-4522-aa83-2c599fb8d675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='edit_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#edit_description</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d5c38a70-a08d-40d4-b975-3e6d0b190e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>77b3a7fa-540d-40bf-9ab6-161e2dc71ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>cc8d1920-10b8-40d1-b828-118f87114414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_description</value>
      <webElementGuid>5c6f3acf-a26e-434f-9799-81b20baf8265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>34243a9a-60bc-43b4-a9af-493f59684871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_description&quot;)</value>
      <webElementGuid>c28f9c6a-adf0-4798-b1a8-f4344f126776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='edit_description']</value>
      <webElementGuid>e83fa5d9-15b5-41c0-a584-04b6400637dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditDocumentType']/div[2]/div[3]/textarea</value>
      <webElementGuid>96ae0bae-c71c-4dab-b852-fb442cbf51a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/div[2]/div[3]/textarea</value>
      <webElementGuid>4b13bb0a-0ff4-49ee-a510-4a47fd833ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'edit_description']</value>
      <webElementGuid>d4b96bf1-8747-454a-a234-09c1569652ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
