<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Back</name>
   <tag></tag>
   <elementGuidId>734efa6d-7b51-49b3-8afe-6f9f16779cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-double-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='table_approvals_previous']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#table_approvals_previous</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bf582607-9175-4ca1-b41a-3d1bee995664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-double-left</value>
      <webElementGuid>b6f905ba-0ea6-4d68-a7b8-c160e8e8a4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6a97e4e-b8b2-4df3-bda4-2c704c2761d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approvals_previous&quot;)/i[@class=&quot;fa fa-angle-double-left&quot;]</value>
      <webElementGuid>b6f57091-b863-4be3-bd44-7a2ce57ee4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='table_approvals_previous']/i</value>
      <webElementGuid>d89f2766-3bdc-487e-b530-b622941c72a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/i</value>
      <webElementGuid>f64ef116-291e-4238-bc19-586b0749a336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
