<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_check_all-My-Approval</name>
   <tag></tag>
   <elementGuidId>d197b367-6d31-4bb1-b02f-223420cc18c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#check_all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='check_all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#check_all</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14e99c1c-ce1d-41fb-84da-0ef68e442e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4625cc45-f79f-4690-97d1-62d20578524a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check_all</value>
      <webElementGuid>dc184e5a-ed95-47b9-aa69-e4a273e46f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check_all&quot;)</value>
      <webElementGuid>2b427567-75bc-478d-9226-a43f639c5b07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='check_all']</value>
      <webElementGuid>8e5533dc-34d4-4a23-bc83-60b18f072d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approvals']/thead/tr/th/input</value>
      <webElementGuid>d37e533e-6b3a-4ce3-8c59-de0c4d5fdfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>5941f22b-36e1-4850-8762-82fc1002d3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'check_all']</value>
      <webElementGuid>cf9c959c-f151-4b5c-a0f6-9b3a968b50be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
