<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Sorting_Amount_My-Approval</name>
   <tag></tag>
   <elementGuidId>59d5fdcb-aa9a-4ab6-a683-b21450d9cee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.text-right.sorting</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_approvals']/thead/tr/th[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Amount: activate to sort column ascending&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>abaf3be1-91d4-4cc0-93f1-67a27a788b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-right sorting</value>
      <webElementGuid>1477059e-74ad-4750-a59f-68c407389707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cbcbcffc-977e-49e3-a8ab-5398568698a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table_approvals</value>
      <webElementGuid>767a8b0e-5efd-4438-a720-ecca9a925213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d96e13a0-de20-4240-b989-2423322a5260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0211fc2c-0743-46e3-9d1c-97032b1a7133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amount: activate to sort column ascending</value>
      <webElementGuid>c3474f82-ecca-4671-be69-1f57a95862b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>1cef375b-dbe2-4641-9762-2f913bedc48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approvals&quot;)/thead[1]/tr[1]/th[@class=&quot;text-right sorting&quot;]</value>
      <webElementGuid>6a645284-6961-43f4-bf68-e9cf7e0f9f6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approvals']/thead/tr/th[6]</value>
      <webElementGuid>e3c07775-5085-432c-8927-51a5cb1a7fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::th[1]</value>
      <webElementGuid>5c72d8cc-b952-46a7-a993-34efba7b2575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[1]/following::th[2]</value>
      <webElementGuid>94ae50ed-651c-43ab-a11f-938761c0442d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::th[1]</value>
      <webElementGuid>9ddd1c92-fb4d-49ac-a95a-a989693226bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data available in table'])[1]/preceding::th[2]</value>
      <webElementGuid>1b2c495c-5060-4c24-b1fa-e61cbbda9066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amount']/parent::*</value>
      <webElementGuid>1f4ace3f-d55a-4c59-9f82-a3bb8b95e173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]</value>
      <webElementGuid>227bfa9d-d3cd-4a3a-ae8b-7cbb77bf0107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Amount' or . = 'Amount')]</value>
      <webElementGuid>e5b6e8bd-586c-4132-88de-b0cbe8a0a8d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
