<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Delete_INV-HJ-021-ALLtab</name>
   <tag></tag>
   <elementGuidId>52a58686-935a-4391-87b8-391ca8bb426c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table_all_invoices > tbody > tr.odd > td.text-center > button.btn.btn-xs.btn-danger.btn-delete > i.bi.bi-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_all_invoices']/tbody/tr/td[10]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>03799e26-4592-4ca8-b7c9-560e85781e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-trash</value>
      <webElementGuid>ff5340ce-9d72-4205-a3c8-30f58826ffaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_all_invoices&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-xs btn-danger btn-delete&quot;]/i[@class=&quot;bi bi-trash&quot;]</value>
      <webElementGuid>f87d9775-e673-4b7b-bba4-2304b414af96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_all_invoices']/tbody/tr/td[10]/button/i</value>
      <webElementGuid>e6fbf8c6-5621-41ef-8095-a7ec0d21ea5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/table/tbody/tr/td[10]/button/i</value>
      <webElementGuid>47181329-39da-4f21-8935-50d9fdf9923d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
