<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select User_AssignUser_2</name>
   <tag></tag>
   <elementGuidId>2152f2d7-c8a8-4110-a6ab-70afe564b3c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-user_assigned-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-user_assigned-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Manto (manto.manto@mmsgroup.co.id)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a2bc8ac-31e5-449c-b7e6-080a5147b17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9e35de68-a830-41b2-8f2c-36d671fb5c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-user_assigned-container</value>
      <webElementGuid>642e9314-141a-46d3-88e3-b093e25726b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c48e55b6-80e9-4b52-b2de-967dae3ddf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a61ec4c-93ce-48d7-9f40-d68f6799ec0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Manto (manto.manto@mmsgroup.co.id)</value>
      <webElementGuid>c92c9a9a-0be0-4f50-b869-f52f310254d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Manto (manto.manto@mmsgroup.co.id)</value>
      <webElementGuid>1e41c17a-1d00-4fe3-bad4-5a8b5bd472e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-user_assigned-container&quot;)</value>
      <webElementGuid>6b029f8d-dbf6-441d-a065-ef5fd2861b3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-user_assigned-container']</value>
      <webElementGuid>046981d4-bbc2-47ad-8209-ae367f42ee3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='assignUserForm']/div/div/div/div/span/span/span/span</value>
      <webElementGuid>7e733574-61d0-4383-b152-2f22a7e76bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User'])[1]/following::span[4]</value>
      <webElementGuid>27871535-3389-4d2e-8b21-5736b524b7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign User'])[1]/following::span[4]</value>
      <webElementGuid>73d9803d-fca3-4777-bbcb-59dff7fb8bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[4]</value>
      <webElementGuid>9043e56a-b327-4369-91a4-aa198d2a66e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>13f21267-0e5a-47b8-8be4-8b0afeaed8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-user_assigned-container' and @title = 'Manto (manto.manto@mmsgroup.co.id)' and (text() = '×Manto (manto.manto@mmsgroup.co.id)' or . = '×Manto (manto.manto@mmsgroup.co.id)')]</value>
      <webElementGuid>5f9fd1fc-bd86-47b3-812f-f63c53817f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
