<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select User_Assign-User_User-Mapping</name>
   <tag></tag>
   <elementGuidId>6651656b-df91-42ea-9fe0-9d3c7f86b000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-user_assigned-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-user_assigned-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Hafiz Jafri (hafizh.jafri@mmsgroup.co.id)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f8d7836-b4e3-483b-8653-8e45d3ab9d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>a4249b0e-e508-4caf-ae54-7168639c9a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-user_assigned-container</value>
      <webElementGuid>a5d3138d-af27-4f9a-9888-952720cb0c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1c8deedb-1b8f-46a5-893c-bb042916da23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>caca8bb0-248e-459d-a6f2-e40eb93b4c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hafiz Jafri (hafizh.jafri@mmsgroup.co.id)</value>
      <webElementGuid>c53a25fb-f12c-439d-92e8-ce30455dfd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Hafiz Jafri (hafizh.jafri@mmsgroup.co.id)</value>
      <webElementGuid>f1a0d2e3-0223-4f78-9934-92d6697ea104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-user_assigned-container&quot;)</value>
      <webElementGuid>9819e5b9-b947-4551-80e1-de0030b03000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-user_assigned-container']</value>
      <webElementGuid>0ca1156b-28a9-49cf-a15a-a5abfd9f6f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='assignUserForm']/div/div/div/div/span/span/span/span</value>
      <webElementGuid>90602fbb-c81f-456d-acb6-39e99887677c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User'])[1]/following::span[4]</value>
      <webElementGuid>0a2d8a4c-c632-40d7-bbdd-c22ef36e1cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign User'])[1]/following::span[4]</value>
      <webElementGuid>868ca230-70e1-4720-9b8a-5e217faed082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[4]</value>
      <webElementGuid>a8307522-6d11-4266-8f74-a8998eb10212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>1aa5a517-8eb8-40a8-b2ee-6442eeca247f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-user_assigned-container' and @title = 'Hafiz Jafri (hafizh.jafri@mmsgroup.co.id)' and (text() = '×Hafiz Jafri (hafizh.jafri@mmsgroup.co.id)' or . = '×Hafiz Jafri (hafizh.jafri@mmsgroup.co.id)')]</value>
      <webElementGuid>f24a67aa-d8e1-4cdf-acfa-894c8f3a7b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
