<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Action_Tab-ALL</name>
   <tag></tag>
   <elementGuidId>622a433d-13ff-4bf5-b02f-1d9a9082af02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_all_invoices']/tbody/tr/td[10]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table_all_invoices > tbody > tr.odd > td:nth-of-type(10) > a.btn.btn-xs.btn-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;PI.25.04.0093 001/0125/NLY/CKT 09-04-2025 David Leonardo 1.000.000,00   Approved  &quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64f59d4f-a353-4b67-ab3e-3ac6e94975bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/purchase_invoices/detail/33</value>
      <webElementGuid>69e1ddf7-ac2b-4821-a1ec-7500782801e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-xs btn-info</value>
      <webElementGuid>933dcb64-2568-4a8f-acf3-d386f0bdc9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_all_invoices&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[10]/a[@class=&quot;btn btn-xs btn-info&quot;]</value>
      <webElementGuid>8be5c319-b13c-409b-b053-3e654ae145a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_all_invoices']/tbody/tr/td[10]/a</value>
      <webElementGuid>cc89ce74-9f05-4b88-9424-a85143a17731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[3]/following::a[1]</value>
      <webElementGuid>73837088-624d-41aa-ac5c-73633fe8f56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='David Leonardo'])[2]/following::a[1]</value>
      <webElementGuid>b2a6a576-774e-44ea-ae4e-1b6819a01159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PI.25.04.0095'])[2]/preceding::a[1]</value>
      <webElementGuid>3f51205e-4201-431a-818b-0373ed2ea07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. Multi Harapan Utama'])[2]/preceding::a[1]</value>
      <webElementGuid>32fb41cb-b07a-475e-84ce-3c37bf572052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/purchase_invoices/detail/33')])[2]</value>
      <webElementGuid>fe06d059-c89b-4f93-9ae2-da069cf1efcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/table/tbody/tr/td[10]/a</value>
      <webElementGuid>235e1597-874b-4959-b700-452e8056167f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/purchase_invoices/detail/33']</value>
      <webElementGuid>3c7926ec-6ee3-45f9-a5dc-1036dca7b8fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
