<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open_no_reference_INV-001-PI-Test</name>
   <tag></tag>
   <elementGuidId>04b10fd6-ca3f-486d-87e3-da63257ee39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td:nth-of-type(2) > a.no_reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;INV-001-PI-Test&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d30e6cb-c1ab-4768-995c-99aad6b4f81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_reference</value>
      <webElementGuid>bf7c0779-b271-45c6-a0bc-439fbf9e0e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/invoice_no?invoice_no=INV-001-PI-Test&amp;from=1</value>
      <webElementGuid>0db5660e-eb3d-4f25-98b6-0481fc2d4760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INV-001-PI-Test</value>
      <webElementGuid>2d201566-e3b3-4716-b1fd-bab4d270c5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approvals&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[2]/a[@class=&quot;no_reference&quot;]</value>
      <webElementGuid>41e53043-c4c7-4168-a7b6-47787a14bee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approvals']/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>8cba0249-77b7-4c0f-9b8e-fca5e4e4e662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INV-001-PI-Test')]</value>
      <webElementGuid>9699311c-7475-4c44-89dd-5a0861d6384a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::a[1]</value>
      <webElementGuid>21b038f2-bd0b-4bc1-92f5-ae47d54a547f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[1]/following::a[1]</value>
      <webElementGuid>42e3e70d-44f8-411c-8fca-0db975d93d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Integra Solusi Mandiri iiii'])[1]/preceding::a[1]</value>
      <webElementGuid>2804d430-b050-4916-bb94-88e81da286fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor teknologi services'])[2]/preceding::a[1]</value>
      <webElementGuid>1fd73d78-d138-4055-9c85-d792567a4c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INV-001-PI-Test']/parent::*</value>
      <webElementGuid>fab0bc87-8724-44a2-be98-41102cbbd42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/invoice_no?invoice_no=INV-001-PI-Test&amp;from=1')]</value>
      <webElementGuid>3aa24eb7-73c4-41b1-b5ae-5d05d5b398ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>a0a90c93-b336-4eaf-a140-4096b31454ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-flowsys.mmsgroup.co.id/purchase_invoices/detail/invoice_no?invoice_no=INV-001-PI-Test&amp;from=1' and (text() = 'INV-001-PI-Test' or . = 'INV-001-PI-Test')]</value>
      <webElementGuid>0af89754-c9b0-4a6a-afaf-b2a8943f5438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
