<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Delete_Approval-Routing</name>
   <tag></tag>
   <elementGuidId>e46db7f6-554b-47ce-b0d7-c9e7cb4d845f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='routing-body']/tr/td[8]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-trash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Delete&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9e60ce13-05e6-4c93-8777-f631098259c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-trash</value>
      <webElementGuid>50653790-fb99-4de1-8a4c-91066e678c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-body&quot;)/tr[1]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-danger btn-xs btn-icon remove-row&quot;]/i[@class=&quot;fas fa-trash&quot;]</value>
      <webElementGuid>e2fda419-8156-440b-8350-403cee99a3da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='routing-body']/tr/td[8]/a/i</value>
      <webElementGuid>6eae822c-5f88-4e97-b0be-4561da360100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a/i</value>
      <webElementGuid>4f0c061a-4d8a-45bb-8c9e-61ac9556df27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
