<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__routing_approver_title</name>
   <tag></tag>
   <elementGuidId>cf185ff3-1ca4-449a-9b22-a93a20d4f78b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='routing[2][approver_title]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;routing[2][approver_title]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;routing\[2\]\[approver_title\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e156d200-d474-4982-ad8e-78af38078fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99e646d4-3a84-4d58-a68a-7a03573e2e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>routing[2][approver_title]</value>
      <webElementGuid>f53f9152-0665-41f0-aa00-4d79da9762eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>67d7cf0c-5322-4af5-aaa1-be586dff520b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-body&quot;)/tr[3]/td[4]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>34147a2d-13f0-4fcd-9436-489d76c1e3ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='routing[2][approver_title]']</value>
      <webElementGuid>8b3de297-f321-4b84-a012-49d30590a368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='routing-body']/tr[3]/td[4]/input</value>
      <webElementGuid>69612f00-ccda-46fa-9a93-af4d551c5fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
      <webElementGuid>22ee15ed-f57c-444a-adea-55ea2a00891b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'routing[2][approver_title]']</value>
      <webElementGuid>f829f119-117d-4069-b148-9b5929e30367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
