<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__routing_max_count</name>
   <tag></tag>
   <elementGuidId>1e19b696-2023-42f9-9bfe-df667443bc7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='routing[2][max_reminder_count]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;routing[2][max_reminder_count]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;routing\[2\]\[max_reminder_count\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a07e644-1690-49a6-be25-4ca3f90653db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f5b17960-a99b-4778-9dde-20b290849f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e0c7239b-f77e-4b25-b5e5-a404cac085d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>routing[2][max_reminder_count]</value>
      <webElementGuid>05d63fba-0826-4e43-9a3d-d0f61f861053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>10cc15b1-0611-476d-95dc-20073ce81d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48052601-084f-4207-b0cc-c4f105df2c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-body&quot;)/tr[3]/td[7]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>b99621ef-f44b-4955-bdd0-a6fda8144e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='routing[2][max_reminder_count]']</value>
      <webElementGuid>7e030ea4-2ff9-4576-aaac-d76149a5f10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='routing-body']/tr[3]/td[7]/input</value>
      <webElementGuid>c394506c-ad73-4ae3-baf7-f5cb3e99dea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/input</value>
      <webElementGuid>489d1e98-c3bc-4854-9e13-609998f68299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'routing[2][max_reminder_count]']</value>
      <webElementGuid>a2466e39-becc-49cd-828c-2da1d18ee278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
