<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__routing_approver_name</name>
   <tag></tag>
   <elementGuidId>1acd7a1a-2956-4cdf-aadd-4aa8f95a562f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='routing[2][approver_name]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;routing[2][approver_name]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;routing\[2\]\[approver_name\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79c5290d-8dc4-4520-aef0-7f34ee5a3a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb021b80-6077-43a2-a831-27353e26a923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>routing[2][approver_name]</value>
      <webElementGuid>3414828a-000e-48da-8c47-8fc1cd77d4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm approver_name ui-autocomplete-input</value>
      <webElementGuid>4e4440e4-3fe9-4a91-aaae-9569f5a9a549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>06103479-cc0a-45da-aa00-31fb4a64d718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-body&quot;)/tr[3]/td[3]/input[@class=&quot;form-control form-control-sm approver_name ui-autocomplete-input&quot;]</value>
      <webElementGuid>9bbaeaae-a1ea-4a3b-83a8-66790fba707d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='routing[2][approver_name]']</value>
      <webElementGuid>0dc14617-40ed-4b5d-a09e-be61077a1dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='routing-body']/tr[3]/td[3]/input[2]</value>
      <webElementGuid>5d81c0be-8d82-4e18-a8a3-980cff50c8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input[2]</value>
      <webElementGuid>a1c792f2-439f-48d6-9b85-7aaa0524188f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'routing[2][approver_name]']</value>
      <webElementGuid>5b2651d1-a641-47f5-92e8-374c6eed9749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
