<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__routing_reminder_interval_days</name>
   <tag></tag>
   <elementGuidId>085a03e1-1504-4bdb-8feb-a0f0051958d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='routing[2][reminder_interval_days]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;routing[2][reminder_interval_days]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;routing\[2\]\[reminder_interval_days\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e8b6b02-1fc7-41d3-a2d1-06d8d4b84cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>48b41504-6dc1-4c26-b2b5-2af1124b999e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5cf0e48c-d0ad-459b-9e5f-18e481efc8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>routing[2][reminder_interval_days]</value>
      <webElementGuid>63ebf49b-6ef9-4dc5-8b18-c48651d3d84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>f711a9e5-309f-4f72-9c2a-7f0d75a128cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>eb79b3d4-6edd-43c6-bd9b-8c42073554ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-body&quot;)/tr[3]/td[6]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>41c14366-f76c-448d-a09a-77aa4538bd1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='routing[2][reminder_interval_days]']</value>
      <webElementGuid>0e305451-4455-4f06-8014-20a322083f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='routing-body']/tr[3]/td[6]/input</value>
      <webElementGuid>1588dfbb-5ef0-491b-965b-a0cda8a661e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/input</value>
      <webElementGuid>2a507e13-114f-4c72-882a-1d26e278cf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'routing[2][reminder_interval_days]']</value>
      <webElementGuid>ecce190e-217e-4632-89f3-5d31a727be07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
