<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__routing_reminder_enabled</name>
   <tag></tag>
   <elementGuidId>c15895a9-dd11-4b2d-abc9-98e3fa1f15a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='routing[2][reminder_enabled]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;routing[2][reminder_enabled]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;routing\[2\]\[reminder_enabled\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c830eb6e-a5d8-4d55-b69c-ef651c02a2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>routing[2][reminder_enabled]</value>
      <webElementGuid>aaf3e511-f177-484f-a8ac-782f665bff25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>d6a449c8-519a-4b45-8aeb-cdf5321abe7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Enabled
                        Disabled
                    </value>
      <webElementGuid>96459fd3-a2dd-47cf-8236-3b2aed079939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-body&quot;)/tr[3]/td[5]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>bb69cebc-246e-49b6-ae28-b41a60bc398a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='routing[2][reminder_enabled]']</value>
      <webElementGuid>2f83eb35-38b5-49dd-b971-fcb667c25b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='routing-body']/tr[3]/td[5]/select</value>
      <webElementGuid>4aaf46f6-258a-45e1-8bb3-311d952f481b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='☰'])[3]/following::select[1]</value>
      <webElementGuid>2843db6e-64a4-4214-a7ef-6c526ab0141c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='☰'])[2]/following::select[2]</value>
      <webElementGuid>623bfeaa-4cce-4310-b13d-4a393a7f36e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/select</value>
      <webElementGuid>7ab46ff4-20b3-4891-8c0f-0ffef2b5f963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'routing[2][reminder_enabled]' and (text() = '
                        Enabled
                        Disabled
                    ' or . = '
                        Enabled
                        Disabled
                    ')]</value>
      <webElementGuid>b9857c16-e886-4abb-970a-91e9958e8fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
