<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Next</name>
   <tag></tag>
   <elementGuidId>f99fec84-7b6e-4123-b3d2-cf0462e53024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-double-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='table_approval_history_next']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#table_approval_history_next</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f0eceae3-9871-464d-aeb5-3163bec01118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-double-right</value>
      <webElementGuid>388bd5e0-9676-49a4-b7be-53b67ae1dc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94417ffc-4c39-41af-8c76-a3251b18a8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approval_history_next&quot;)/i[@class=&quot;fa fa-angle-double-right&quot;]</value>
      <webElementGuid>7c4ce3e2-40ed-4931-a8a0-e8a43d1347c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='table_approval_history_next']/i</value>
      <webElementGuid>5b1c37c8-acf8-4621-aef3-3644883fe913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>d1b9909c-b71c-4263-a353-ce7e7e9878b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
