<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings-Menu</name>
   <tag></tag>
   <elementGuidId>abfe0ce6-60b1-45d9-a8a8-fbd1a749265d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu']/li[4]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mm-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Settings Menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>20a657f8-7cfd-44ee-ab91-a0ff2c5825a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat-flowsys.mmsgroup.co.id/settings/access</value>
      <webElementGuid>10afbaaa-bed7-4079-a050-c24377cfeac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mm-active</value>
      <webElementGuid>04a32919-b8af-44b5-ae21-6a015c1e40fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings Menu</value>
      <webElementGuid>fe45bc6d-da89-4b11-9f77-5a8c280ee889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/li[@class=&quot;1 mm-active&quot;]/ul[@class=&quot;mm-collapse mm-show&quot;]/li[@class=&quot;mm-active&quot;]/a[@class=&quot;mm-active&quot;]</value>
      <webElementGuid>5a53b0c2-8dd9-48a1-b5d0-4c2aa04c716d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu']/li[4]/ul/li[2]/a</value>
      <webElementGuid>182f9f8e-8e3c-4b16-8cd6-2fbe6fe53905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Settings Menu')]</value>
      <webElementGuid>41caed03-f35e-43de-b3a1-c1b9947acac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings Role'])[1]/following::a[1]</value>
      <webElementGuid>aca7de7f-479f-49c2-b60b-5c8cea083bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::a[2]</value>
      <webElementGuid>21397ad7-84e2-486d-8d04-56d368474c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings User'])[1]/preceding::a[1]</value>
      <webElementGuid>ef2d52e3-5add-4b77-b923-fc3ffc8a10e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Type'])[1]/preceding::a[2]</value>
      <webElementGuid>f8b7dff4-ec8d-4e12-8312-a0e6f4067ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Settings Menu']/parent::*</value>
      <webElementGuid>d5485aa3-f344-4b0c-85b0-dfea825e2a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat-flowsys.mmsgroup.co.id/settings/access')]</value>
      <webElementGuid>5aafc237-d694-4601-b740-d616fa011320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>b7dff00e-4879-4c81-bb35-dd26c1cde1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat-flowsys.mmsgroup.co.id/settings/access' and (text() = 'Settings Menu' or . = 'Settings Menu')]</value>
      <webElementGuid>79ca517f-6925-409c-aedb-300bffeeb42a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
