<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prefix_EDIT_Tab-Action_Settings-Menu</name>
   <tag></tag>
   <elementGuidId>c74af745-8967-4068-8606-c20d764eb66d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accessPrefix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accessPrefix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Prefix&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f1f2ced-954c-4942-9215-3a184efef590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63372ac3-09ee-4b34-a522-a0fc81226636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ea8944d6-977b-41ea-ae19-50d72f656560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accessPrefix</value>
      <webElementGuid>d37b1380-3e12-42a4-8e7f-3e82a9437505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prefix</value>
      <webElementGuid>78fb8627-51f9-4ed0-b5a8-462bbea3df7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter prefix</value>
      <webElementGuid>9facfec5-39c6-4f89-9b4c-1aa46565678f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accessPrefix&quot;)</value>
      <webElementGuid>709bff44-9e11-4446-9279-f9909db3cab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accessPrefix']</value>
      <webElementGuid>015c6fb2-f0ba-4793-913c-9da946db40fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='updateAccessForm']/div[2]/div[3]/input</value>
      <webElementGuid>543e6244-9750-45ce-8766-cb67758252c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/form/div[2]/div[3]/input</value>
      <webElementGuid>943880ed-712c-46b5-8e7c-6bb79c740871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'accessPrefix' and @name = 'prefix' and @placeholder = 'Enter prefix']</value>
      <webElementGuid>e2ee89dd-d255-401b-aa1b-81d1258a764e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
