<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Label_EDIT_Tab-Action_Settings-Menu</name>
   <tag></tag>
   <elementGuidId>2fd07f6a-c792-4873-8a70-6c5c23dfbfcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accessLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accessLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Label *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e14918e0-d2d3-4094-beeb-4ae8eee69a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7637070e-806a-4fd7-899d-bf23091f356c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6dfae611-ba67-456b-883f-c973de7b0779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accessLabel</value>
      <webElementGuid>5bbd6e2e-e090-4eba-8dff-f63825384376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ff85e0a4-099a-4f0b-999c-e882df56bc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter label</value>
      <webElementGuid>be10fb37-9f3e-4670-9fcc-5fa9d6753ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accessLabel&quot;)</value>
      <webElementGuid>fa0c0e6a-037a-44de-962b-cd5f5d0ecf9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accessLabel']</value>
      <webElementGuid>6f3cfa3c-dbec-4d1c-a753-8eb3ee065771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='updateAccessForm']/div[2]/div[2]/input</value>
      <webElementGuid>3d5748fc-a63c-4bc9-a9cd-15e44d292696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>ece63931-c337-473c-a499-0aa85051ffb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'accessLabel' and @name = 'label' and @placeholder = 'Enter label']</value>
      <webElementGuid>ddf1b22a-70b6-4e5a-8387-ae3e9a5a8602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
