<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__approval_routing_name</name>
   <tag></tag>
   <elementGuidId>e8db9d53-348a-46e5-8dae-9bba902df476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='approval_routing_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;approval_routing_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;approval_routing_name&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6050e8ae-ec28-4e14-b457-a187c8a02297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d95fe670-f0e4-470c-85c0-09100a35a488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>approval_routing_name</value>
      <webElementGuid>a6f64536-7fbc-43ae-b10a-cbe361e08892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>a15e9132-e9f8-413e-b479-745461bc40a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test 001</value>
      <webElementGuid>6c29d6ca-4c03-4a2b-b9de-8208bc5003ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formEditWorkflowSetup&quot;)/div[@class=&quot;col-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body pt-2 form-general&quot;]/div[@class=&quot;row gx-5&quot;]/div[@class=&quot;col-12 row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-sm-8&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>98fdbe85-4667-4a77-806d-02677e32ddb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='approval_routing_name']</value>
      <webElementGuid>5bf3cba5-8cdd-453d-b779-943e84c9a15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditWorkflowSetup']/div/div/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>fd1ae08e-c968-47a9-abc1-658417825b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e60dd8d1-bf62-4441-a7ce-991709b6b5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'approval_routing_name']</value>
      <webElementGuid>b3dfe0d3-6d3d-4e0a-af38-7b87dbe855da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
