<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maximum-Amount</name>
   <tag></tag>
   <elementGuidId>a5a97706-ec3e-422a-a919-d858d3006d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='maximum_amount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;maximum_amount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;maximum_amount&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>648ddcbe-a41a-430a-875d-b4acfa5a7e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f856f1f-3229-4e89-a094-730d508d161c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maximum_amount</value>
      <webElementGuid>adf311d3-df21-4467-a6a1-b19826401ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm format-rupiah</value>
      <webElementGuid>9edad1f6-e480-4aab-9c32-848ec3bc1e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.000.000</value>
      <webElementGuid>4707439c-d811-4145-a896-842bd003974c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formEditWorkflowSetup&quot;)/div[@class=&quot;col-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body pt-2 form-general&quot;]/div[@class=&quot;row gx-5&quot;]/div[@class=&quot;col-12 row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-sm-9&quot;]/input[@class=&quot;form-control form-control-sm format-rupiah&quot;]</value>
      <webElementGuid>9f2be917-5ed2-4d0b-92ed-627f41cd9568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='maximum_amount']</value>
      <webElementGuid>0c1f0e9f-722b-4fe4-a6f7-b367ccb09fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditWorkflowSetup']/div/div/div[2]/div/div/div[2]/div[3]/div/input</value>
      <webElementGuid>7a2fa34f-e67e-4b45-9739-7b15a97382a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>1609f42b-686d-464c-a957-fe57d0b6a6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'maximum_amount']</value>
      <webElementGuid>f7344898-20ee-4b28-9e48-fbb21ee2728e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
