<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Status</name>
   <tag></tag>
   <elementGuidId>97b3918c-6f45-4341-8ca2-7e7d5427fd3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;status&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;status&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1969abd1-ef88-4723-ae1a-22313282c678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>df446813-b8f8-4355-adb6-4c5bb91a3bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>5d3850b8-8d2a-4be7-bdc6-e29c2bb4f892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3b048998-7e43-4e28-9382-7cbcf83b3396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Active
                    Inactive
                </value>
      <webElementGuid>e007a7a5-603d-4c28-a3d8-7336880ae334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formEditWorkflowSetup&quot;)/div[@class=&quot;col-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body pt-2 form-general&quot;]/div[@class=&quot;row gx-5&quot;]/div[@class=&quot;col-12 row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-sm-9&quot;]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>782eadca-0f6b-48d6-9aef-e96057788716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='status']</value>
      <webElementGuid>c10c2f67-bbc0-4e29-93dd-6024d2983722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formEditWorkflowSetup']/div/div/div[2]/div/div/div[2]/div/div/select</value>
      <webElementGuid>28bf1d60-801c-4ce1-b9da-7a2aa8c8b4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>a160c1ac-3018-4bd7-bb2b-44778dce98fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated At'])[1]/following::select[1]</value>
      <webElementGuid>671b4cad-452a-4dfb-931e-84e580e76da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Amount'])[1]/preceding::select[1]</value>
      <webElementGuid>dd551c98-0215-4662-899e-b586dd508b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Amount'])[1]/preceding::select[1]</value>
      <webElementGuid>f8f4a76f-d31b-41a9-be98-18d95189d46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>6bf7cc00-a9f2-40c4-bdf2-24a3818b348c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status' and (text() = '
                    Active
                    Inactive
                ' or . = '
                    Active
                    Inactive
                ')]</value>
      <webElementGuid>fe617dc7-512f-44b5-a131-86d77bf1063d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
