<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_PRINT_FormPI_Approved</name>
   <tag></tag>
   <elementGuidId>131282c8-d27d-4795-8f89-8d2cb5829b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-content']/div/div/h4/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-print.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>87fd9b63-c963-4f49-939d-6e6a1a544d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-print text-primary</value>
      <webElementGuid>8c84b244-c6c9-4428-92fa-329246a00b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-content&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header d-flex justify-content-between align-items-center&quot;]/h4[@class=&quot;card-title mb-0&quot;]/a[1]/i[@class=&quot;fas fa-print text-primary&quot;]</value>
      <webElementGuid>7e15155c-e907-4b8f-b576-3a475020f1e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-content']/div/div/h4/a/i</value>
      <webElementGuid>57f9d8bb-8d33-4b9f-bf01-86a0b5a6db82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a/i</value>
      <webElementGuid>23058981-a3ff-46c2-89b8-593d7202a5b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
