<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Sorting_Document-Type_Invoice-Type</name>
   <tag></tag>
   <elementGuidId>bb331e80-8da3-4fc3-8b4b-5d03fa5239e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.text-center.sorting</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_invoice_type']/thead/tr/th[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Document Type: activate to sort column ascending&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>f2cbb845-fef1-4989-b282-ace060888fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center sorting</value>
      <webElementGuid>abe7371d-1b8d-4a45-8d42-2e3e50e72b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a7692d8-214e-4cca-9a27-e3b363d3c691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table_invoice_type</value>
      <webElementGuid>3a0574a3-11f5-47b9-9037-6ff822c9cef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>92770b73-d65d-4115-ae0c-4e2298750d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>750cd036-e61f-405e-bfe1-377585e1feb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Document Type: activate to sort column ascending</value>
      <webElementGuid>875e7176-3372-4812-9bda-565b041655bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Document Type</value>
      <webElementGuid>3194e15c-780e-42f6-830b-23a5ce03b96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_invoice_type&quot;)/thead[1]/tr[1]/th[@class=&quot;text-center sorting&quot;]</value>
      <webElementGuid>46dcb0b6-5845-4178-bf00-c77886b8a1f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_invoice_type']/thead/tr/th[4]</value>
      <webElementGuid>2f7df1b6-9bfc-44dd-8515-c443c9a8f124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::th[1]</value>
      <webElementGuid>381756e3-2d4b-4b95-ad6c-10c8559df204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/following::th[2]</value>
      <webElementGuid>60f480ae-fd9c-4499-8b12-64b53c2c323a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::th[1]</value>
      <webElementGuid>e1e24948-1a3e-4679-99ef-83eb9943cb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::th[2]</value>
      <webElementGuid>ae9c9f06-1641-4f7e-ba81-b009d21c06e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]</value>
      <webElementGuid>4c32e045-f520-458d-9a44-9ed173bc0ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Document Type' or . = 'Document Type')]</value>
      <webElementGuid>54b6db25-ed9e-4608-868f-ce31a3bdc9c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
