<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Edit_Workflow-Setup</name>
   <tag></tag>
   <elementGuidId>8950d41c-ac98-4fb4-9e30-38764cec97b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_workflow_setup']/tbody/tr/td[7]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-pencil-square</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>eebb940e-9ca9-4e2f-b4e7-39cfecf3882d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-pencil-square</value>
      <webElementGuid>caf28010-0dcd-459c-b272-20f400922af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_workflow_setup&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-xs btn-primary&quot;]/i[@class=&quot;bi bi-pencil-square&quot;]</value>
      <webElementGuid>7c558424-5262-47d7-bbcd-48b1f7f43b1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_workflow_setup']/tbody/tr/td[7]/a/i</value>
      <webElementGuid>0989a5ba-778b-4dcc-b191-ec5758f616ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/i</value>
      <webElementGuid>c0559921-c2fa-4974-b6af-5392cef6f885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
