<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Sorting_FormNo-ALL</name>
   <tag></tag>
   <elementGuidId>677b0a79-f926-4c49-8de6-36a57541d6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_all_invoices']/thead/tr/th[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table_all_invoices > thead.table-light > tr > th.text-wrap.sorting</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Form No: activate to sort column ascending&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>dbcf922b-d5d4-455c-be9c-ee58971fe2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-wrap sorting</value>
      <webElementGuid>ce17c63f-8b8f-4d85-99cb-ee17ed50293a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8cd52e83-ad2f-4219-9d5d-755e5bf466c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table_all_invoices</value>
      <webElementGuid>5883bb73-6cce-4658-a4a7-b33ac86c2c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6e4be432-0d93-40b4-8c80-e2e9a64136fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1d3e6df9-8499-42aa-9a12-ea417c3c709b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Form No: activate to sort column ascending</value>
      <webElementGuid>c0900b8d-897f-4a49-8122-ab7d535cf256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form No</value>
      <webElementGuid>00ec64a2-bb99-4882-8b13-063d7a01351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_all_invoices&quot;)/thead[@class=&quot;table-light&quot;]/tr[1]/th[@class=&quot;text-wrap sorting&quot;]</value>
      <webElementGuid>5975f3d3-19d2-42eb-bcd7-d7a290fb8ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_all_invoices']/thead/tr/th[2]</value>
      <webElementGuid>481fbc0a-8a8f-409f-85f2-8f0248c8f404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[4]/following::th[2]</value>
      <webElementGuid>08878ceb-07cb-4065-a93b-5cb69a6aa9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[4]/following::th[2]</value>
      <webElementGuid>01f25f7b-1403-4482-8397-d09da214cc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice No'])[4]/preceding::th[1]</value>
      <webElementGuid>b41a12c9-6db9-47ec-a162-b0ccbf2a69e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Date'])[4]/preceding::th[2]</value>
      <webElementGuid>b34b96a1-d04f-458b-92ce-3e65af39b706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/table/thead/tr/th[2]</value>
      <webElementGuid>e05b05a5-0601-4c81-9aab-274edc430dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Form No' or . = 'Form No')]</value>
      <webElementGuid>4c90d95f-7ccf-4c9f-843f-944a8c3f49f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
