<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select-checkbox-Open</name>
   <tag></tag>
   <elementGuidId>aa94d9ac-40f3-4dac-98c6-e0c58b4fa127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='34']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.select-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;PI.25.04.0095 026/MHU-MMI/DN/III/2025 09-04-2025 PT. Multi Harapan Utama 1.000.000,00   Open &quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d76bcd53-a16a-4ded-98d6-f87f7ed4516b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5b659b53-9921-4370-b7c9-df7cd0de4ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-checkbox</value>
      <webElementGuid>69c6d7e6-3f0e-43f3-8f10-105c07f940ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>cf642cd8-5b93-423b-a4d1-ee92d21868d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cansubmit</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25e9e616-8bfc-4d4c-8531-73cd1b698ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_open_invoices&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center sorting_1&quot;]/input[@class=&quot;select-checkbox&quot;]</value>
      <webElementGuid>b2376544-4668-4e2d-af2c-3c15bf5b7551</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='34']</value>
      <webElementGuid>fed48dcd-cb04-404f-a018-60369d901155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_open_invoices']/tbody/tr/td/input</value>
      <webElementGuid>5c66b1b3-dce9-4d6a-9805-088ba21ee09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>8ef0ec25-e4fb-458e-97e2-079080208ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>8f1bebdb-4f73-49b0-b093-4b6b8f4afe5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
