<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Showentries_table-Open</name>
   <tag></tag>
   <elementGuidId>9c156843-2749-4475-935c-44998867dd11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='table_open_invoices_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;table_open_invoices_length&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open&quot;i >> internal:label=&quot;Show 102550100 entries&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0d1887c8-8f0f-4d31-9d37-715c92e6d181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table_open_invoices_length</value>
      <webElementGuid>ec3c8168-db22-4e4d-9a51-2d347a2d36d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table_open_invoices</value>
      <webElementGuid>d04d11f0-6837-473b-a86e-9286fa2aef81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>a8f4d57c-53aa-4701-a899-f444778d51ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_open_invoices_length&quot;)/label[1]/select[1]</value>
      <webElementGuid>13c93c29-fa0a-493c-921f-ceb92cd8c81b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='table_open_invoices_length']</value>
      <webElementGuid>5f5ad6ac-a737-4987-9f62-f71c9ebf83c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table_open_invoices_length']/label/select</value>
      <webElementGuid>e37511aa-ae3a-4891-ba62-7803302a5596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[2]/preceding::select[1]</value>
      <webElementGuid>41a539f0-29b0-4844-960f-e4c0e16f7062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[2]/preceding::select[1]</value>
      <webElementGuid>a3daf56d-2e19-46a2-8ec3-f3fdab03706a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/label/select</value>
      <webElementGuid>afd361ca-cf37-4297-9ede-fab65eb2d289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'table_open_invoices_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>9fd2409f-afa0-445f-8123-803d545b4c8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
