<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_select-checkbox</name>
   <tag></tag>
   <elementGuidId>a5fa276d-dba2-49fb-b88f-29fe35aee315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='33']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table_approved_invoices > tbody > tr.odd > td.text-center.sorting_1 > input.select-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;PI.25.04.0093 001/0125/NLY/CKT 09-04-2025 David Leonardo 1.000.000,00   Approved &quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9f0d3be-da02-412e-a433-da6c39fd5c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>63600be7-dd00-4469-97d2-d0948abf444d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-checkbox</value>
      <webElementGuid>74350cf3-bb25-4fcf-98dc-51e1057febf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>06043656-eee4-4a8f-9282-623a977e2e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cansubmit</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a63d951d-c18c-4abd-97ae-a857d9b5c920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approved_invoices&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center sorting_1&quot;]/input[@class=&quot;select-checkbox&quot;]</value>
      <webElementGuid>4c47465e-a104-4fa0-94af-43fae82bd401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='33']</value>
      <webElementGuid>67a88f6d-beb7-4683-bdf2-d2bc046dc9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_approved_invoices']/tbody/tr/td/input</value>
      <webElementGuid>44f8a90c-8963-413b-812d-ed08e7e21ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>c7675914-313f-4acd-a987-519a4f20d40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>4b3e66dc-e924-4c8b-ba4b-c3e7ea97293a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
