<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Showentries_approved</name>
   <tag></tag>
   <elementGuidId>1ba9a243-b258-4116-8d3f-ad6b188f928c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='table_approved_invoices_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;table_approved_invoices_length&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Approved&quot;i >> internal:label=&quot;Show 102550100 entries&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5627c5d2-96bf-4855-9c1b-be18f968b791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table_approved_invoices_length</value>
      <webElementGuid>232b41f7-7f60-4892-aded-d64d5645f73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table_approved_invoices</value>
      <webElementGuid>ba16cc0b-c686-4b82-bd42-99595926498a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>034fa78f-23df-4a68-89f8-9deeb2cb4003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_approved_invoices_length&quot;)/label[1]/select[1]</value>
      <webElementGuid>6f1db609-4667-4901-90cb-d9f86bf18ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='table_approved_invoices_length']</value>
      <webElementGuid>faeb30ea-1787-4ebc-91bc-c58f4e35f5b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table_approved_invoices_length']/label/select</value>
      <webElementGuid>2a925c5c-f7aa-4e6c-ab00-37312426d9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[3]/preceding::select[1]</value>
      <webElementGuid>72fbb67c-66f4-4a3c-8f83-f32e723e0cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[3]/preceding::select[1]</value>
      <webElementGuid>b496db42-232c-4965-a367-b302bddbf7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/label/select</value>
      <webElementGuid>2190a8b7-5949-4cd4-bcb3-46441fac7457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'table_approved_invoices_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>bc05b0eb-3492-48ec-9231-78d1b41fc569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
