<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Print Form purchase invoice_Tab ALL</name>
   <tag></tag>
   <elementGuidId>23b7537c-604d-459b-af6b-899e9fc7e86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-content']/div/div/h4/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-print.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4fef5968-c40d-464d-a0be-21cd05d0bbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-print text-primary</value>
      <webElementGuid>29b01354-f3da-4e83-823f-d4e72d0dbcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-content&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-header d-flex justify-content-between align-items-center&quot;]/h4[@class=&quot;card-title mb-0&quot;]/a[1]/i[@class=&quot;fas fa-print text-primary&quot;]</value>
      <webElementGuid>0a30a032-c2e3-4b6e-94af-4f79c74d4161</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-content']/div/div/h4/a/i</value>
      <webElementGuid>b6b71c48-5e8f-43a1-9436-469a0574cc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a/i</value>
      <webElementGuid>3ed4823b-fffb-4cba-943f-10bbd12fd93e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
