<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Role_UserManto_IN_SettingUser</name>
   <tag></tag>
   <elementGuidId>e3341264-b32d-4504-b0cc-4cb28b8f2cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > a:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_user']/tbody/tr[3]/td[3]/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;- Super Admin - Accounting User - Flowsys Admin - System Admin - User&quot;i] >> internal:role=link >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>956fa63c-fb20-431c-a6cc-932e0ea43a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/role-user/3</value>
      <webElementGuid>a0e5a06c-809d-407d-af06-c24aa9b77d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>192fac91-ec8f-40f6-92bb-60ffaafb0f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_user&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]/a[5]</value>
      <webElementGuid>9795cae0-2b6c-4b9c-95c5-affe06f69283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_user']/tbody/tr[3]/td[3]/a[5]</value>
      <webElementGuid>4ae7709b-805d-4e02-8529-8eefa63935c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'User')])[12]</value>
      <webElementGuid>273e0f31-5065-45ee-9439-a8679bf317d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Admin'])[3]/following::a[1]</value>
      <webElementGuid>c584b9db-1f16-496e-9849-1d7542cf2ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flowsys Admin'])[3]/following::a[2]</value>
      <webElementGuid>9825be5a-f257-41a6-97cd-35badffb189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[3]/preceding::a[1]</value>
      <webElementGuid>5649ed8a-1686-40e0-9a61-a802e2b0883f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::a[1]</value>
      <webElementGuid>bfe9917f-5a14-489d-b781-ab0be0644add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/settings/role-user/3')])[3]</value>
      <webElementGuid>1dcb3606-a966-4c79-b094-98e8b867f07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a[5]</value>
      <webElementGuid>43894a81-74cc-40a5-a6ce-e1ad65f79c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/settings/role-user/3' and (text() = 'User' or . = 'User')]</value>
      <webElementGuid>b3712363-ee50-4428-9908-083621352971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
