<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Next</name>
   <tag></tag>
   <elementGuidId>87a0050c-2698-49e2-8e19-095d6af985c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-double-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='table_user_next']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#table_user_next</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>01e64d8c-6f6a-4073-bac4-8ecc30b9053f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-double-right</value>
      <webElementGuid>df8e6a87-2382-453f-a60c-8a38bb90870f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>195804a2-981e-4e05-a38b-51fc4ff57c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_user_next&quot;)/i[@class=&quot;fa fa-angle-double-right&quot;]</value>
      <webElementGuid>5a9319e4-6ff0-4394-a71f-3371e1e1e5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='table_user_next']/i</value>
      <webElementGuid>2b21e4f0-8c09-412f-962d-13644b80f579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>88be8bd4-d613-4c2f-854a-f8c0e203bdba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
