<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Update_Access_Add-Delete</name>
   <tag></tag>
   <elementGuidId>6aacd284-0dbc-4181-a9b7-6383c2483a99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add_delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add New Access&quot;i >> internal:label=&quot;Delete&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0054298b-7eea-47d8-bd98-8e23fd29f44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ea087114-f314-4bac-98b8-009f0cfb918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f23d8804-5184-45ab-8c4a-42d78f11e3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_delete</value>
      <webElementGuid>ba4c589d-ca74-4d00-8678-fe164ceea917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>ff3ccd0c-60fb-4dec-b8a8-b2d6175a8a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>58eef41a-8497-4cc8-9a69-cf48fb1fed19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_delete&quot;)</value>
      <webElementGuid>7fd55f06-b991-402d-a7ed-58158c1f26d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add_delete']</value>
      <webElementGuid>60b6b7b8-ec43-47d8-b02b-fa501b9cdf57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='assignAccessForm']/div/div[9]/div[4]/input</value>
      <webElementGuid>6cca9b3b-d95d-4da1-9cd4-e1c8085e9b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[4]/input</value>
      <webElementGuid>d01964af-82e8-47b5-bc12-72d93bf4429a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'add_delete' and @name = 'delete']</value>
      <webElementGuid>b2418fdf-c067-4c03-9fff-fa59e61114fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
