<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Access_select-Menu-Access</name>
   <tag></tag>
   <elementGuidId>bc19768e-6190-4989-96e1-ce5ab32c826a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-select_access_id-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-select_access_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-select_access_id-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>097d799e-365b-415a-8bd5-47d68f9667a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>af040790-a545-4fe1-b9de-b3cdb3b836d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-select_access_id-container</value>
      <webElementGuid>27897ad2-cdf4-4388-bbd4-581895f1f57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>20578f5e-fecc-43bb-b44c-49571f030a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8841a0e-585d-497e-b9ad-38db05dadad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Access</value>
      <webElementGuid>fc1c67b3-9db1-42d7-a01b-81897dc5c3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-select_access_id-container&quot;)</value>
      <webElementGuid>9f99b4ef-33e9-4c13-bc17-731a55e19e7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-select_access_id-container']</value>
      <webElementGuid>224a8295-7a08-483f-a477-1b0c6359b5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAccess']/div/span/span/span/span</value>
      <webElementGuid>fd3abd60-b501-4a5e-a8c4-707506bb2c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access'])[1]/following::span[4]</value>
      <webElementGuid>f7594e41-73a2-4cd2-8723-a0715533d8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Access'])[1]/following::span[4]</value>
      <webElementGuid>dc590741-e508-435a-9e21-36314d4764ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::span[4]</value>
      <webElementGuid>ca35842a-843c-4c79-b236-c84dde0b2121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>08fdc956-266f-481e-bfb1-478b7e00b426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-select_access_id-container' and (text() = 'Select Access' or . = 'Select Access')]</value>
      <webElementGuid>6e2a08e6-8203-49a4-823b-558af0fbfe2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
