<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supporting Document_SubCancel</name>
   <tag></tag>
   <elementGuidId>338a15e3-ff6e-4c15-a64c-c5862796e7c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#supporting_document</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supporting_document']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#supporting_document</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4ce1fcb-89e5-4889-b648-46e96f43c574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>eb351bbb-20d5-4bb0-a058-02f1ff388c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supporting_document</value>
      <webElementGuid>eb87f4bd-0010-4b1f-ac49-5f1bed97a844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm mb-3</value>
      <webElementGuid>89e9289a-73e0-43d6-bb20-398c9f98a5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf,.jpg,.jpeg,.png</value>
      <webElementGuid>0a1b165a-f384-43c2-bfbc-ae9d62c44f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supporting_document&quot;)</value>
      <webElementGuid>d49827a7-2e06-4623-bcb0-770dcef97974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supporting_document']</value>
      <webElementGuid>6abe68f6-7723-4a0c-a80e-d5a2d83019c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']/div/input</value>
      <webElementGuid>82a87d68-b369-4cf4-867b-429ab4751cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>c14243ca-c740-48bb-afbd-5413b2013aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'supporting_document']</value>
      <webElementGuid>ef5a0b1d-de9b-4ceb-a7c3-06741e81d274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
