<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes (Optional)_note_submit</name>
   <tag></tag>
   <elementGuidId>7fdf4fca-221c-4cdc-a2df-793a1e45e6b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#note_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='note_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Add any remarks or additional information for the approver&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6810dc4a-78cf-405b-b73f-6ac54d5952e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>note_submit</value>
      <webElementGuid>8e07bc1e-6cbd-478f-afad-96a07cf56410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-3</value>
      <webElementGuid>663a2c4c-8ab9-44d4-9bff-b13f59afef5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6bcc645d-5fa0-42ec-bbd3-dda79b100877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add any remarks or additional information for the approver</value>
      <webElementGuid>39212a2c-9f04-44b0-b7b7-82cd8081a232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note_submit&quot;)</value>
      <webElementGuid>65ec8f92-9dc9-4a00-946f-38a347fdd9ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='note_submit']</value>
      <webElementGuid>2469c0e6-f505-48b5-ba41-b2399327715c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swal2-html-container']/div/textarea</value>
      <webElementGuid>ff1caa1e-3a35-4522-8afc-c4919920597a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>0c3c7508-866d-4ea4-9451-03631b89e7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'note_submit' and @placeholder = 'Add any remarks or additional information for the approver']</value>
      <webElementGuid>e0ad215f-87a0-43d8-9e3a-778c4a827c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
