<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_User</name>
   <tag></tag>
   <elementGuidId>e146b133-ccaf-4123-9dcc-4acfed9dc009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.text-muted.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div[2]/div/nav/div/div[2]/div/div[2]/ul/li/div/div[2]/div[2]/ul/li/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;User&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10dc971e-f50d-4bd5-8e89-5a440cff6986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-muted dropdown-item </value>
      <webElementGuid>a5eeef1c-8222-4ec7-9fd3-3d33239066ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>260e3188-2a63-4627-b4bb-142f23cdcc91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role_id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c7cfe11f-8035-4ee1-908a-bc5b2f8e7636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                            User
                                                                        </value>
      <webElementGuid>2dd34f84-2b56-41e6-ac4a-7c8a86285bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;header&quot;]/div[@class=&quot;header-content&quot;]/nav[@class=&quot;navbar navbar-expand&quot;]/div[@class=&quot;collapse navbar-collapse justify-content-between&quot;]/div[@class=&quot;navbar-nav header-right&quot;]/div[@class=&quot;nav-item d-flex align-items-center&quot;]/div[@class=&quot;input-group&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item dropdown header-profile&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[2]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item dropdown header-role&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-end role_menu show&quot;]/li[2]/a[@class=&quot;text-muted dropdown-item&quot;]</value>
      <webElementGuid>fea6e0a5-c4c2-48c0-8b37-0546988362ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[2]/div/nav/div/div[2]/div/div[2]/ul/li/div/div[2]/div[2]/ul/li/ul/li[2]/a</value>
      <webElementGuid>9235f43d-4942-490c-bdd1-c41d44d4d5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'User')])[2]</value>
      <webElementGuid>d0ca5474-6cc1-4b72-b2f0-3c8c52807cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[3]</value>
      <webElementGuid>51ad7052-d705-493f-a2f6-7e069088f750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[1]</value>
      <webElementGuid>eb6672fc-8384-43a6-9716-ae82c7a9cdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Session Expired'])[1]/preceding::a[1]</value>
      <webElementGuid>63b3411c-705d-40a3-848b-6f19d359df14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>f4ecc6f3-dab8-4a9e-aa6a-e749e3185366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>92f0cb64-5e05-4d57-aee0-11f7a606ee5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                                                                            User
                                                                        ' or . = '
                                                                            User
                                                                        ')]</value>
      <webElementGuid>df896b18-451c-417c-ac47-6ad02db34479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
