<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Change-User</name>
   <tag></tag>
   <elementGuidId>ca3abd83-046f-4203-bd1b-5f1ff98f5647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#role-caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='role-caret']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Super Admin &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>397c1ff3-c96b-4632-811b-c1a248552641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-caret-down</value>
      <webElementGuid>4cd6e3f0-9a44-4512-b9b1-da6bf9253993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>role-caret</value>
      <webElementGuid>11273cad-3d05-4bbc-bc29-3bb10928de6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role-caret&quot;)</value>
      <webElementGuid>f5502c29-aa05-40b6-84e8-df70401eb246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='role-caret']</value>
      <webElementGuid>4ed84972-afcf-43b4-b7f7-207e4c4ee592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[2]/div/nav/div/div[2]/div/div[2]/ul/li/div/div[2]/div[2]/ul/li/a/i</value>
      <webElementGuid>bc8c6384-a6b5-4d0f-9926-4493f604a978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>93c013d2-8f91-4140-a3b4-a95294fc5685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'role-caret']</value>
      <webElementGuid>7edd94a1-f3ce-4329-a616-c47e0d502233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
