<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Processing_check_all_open</name>
   <tag></tag>
   <elementGuidId>2fbfc503-da58-4519-af25-42ae2eca31b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#check_all_open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='check_all_open']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#check_all_open</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e066006-ee28-4abe-846b-890de56f8766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c2fa20e1-224d-49e3-9272-cc3ddbad4f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check_all_open</value>
      <webElementGuid>7638f58f-5dba-45a7-b26c-ff523b125ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check_all_open&quot;)</value>
      <webElementGuid>c8cff50c-1420-4601-b673-bd48d74016ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='check_all_open']</value>
      <webElementGuid>89b9ccf0-5d95-43a3-b11a-31960fd3d396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_open_invoices']/thead/tr/th/input</value>
      <webElementGuid>9f2f96ed-b7aa-4552-8087-7b2749335f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/table/thead/tr/th/input</value>
      <webElementGuid>28076370-503e-4716-80fd-e33e99cbd71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'check_all_open']</value>
      <webElementGuid>30a7711f-78ed-4d43-bf5e-40e4f2d7baeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
