<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Amount</name>
   <tag></tag>
   <elementGuidId>99139d22-c4c6-4d55-a37a-64647df3a6d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table_open_invoices > thead.table-light > tr > th.text-right.sorting</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_open_invoices']/thead/tr/th[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Amount: activate to sort column ascending&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>33bd779d-ff39-4c2d-a431-dd05ac9c1981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-right sorting</value>
      <webElementGuid>7890a052-3cc0-4c9a-b27f-3e8f3a0bd28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8bf6c9c-894d-4a64-8509-6dcc065afe2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table_open_invoices</value>
      <webElementGuid>385d4226-b9c4-49a7-94e9-e9c682a3f207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7609af4e-7667-4f0d-bee3-9f512e15e6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5b80bf28-d964-45d6-9fe5-8cc12aa2095a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amount: activate to sort column ascending</value>
      <webElementGuid>a6aabb22-867b-4eb7-98b7-599626891617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>52747d7d-8bef-4bac-9211-974bc20a0a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_open_invoices&quot;)/thead[@class=&quot;table-light&quot;]/tr[1]/th[@class=&quot;text-right sorting&quot;]</value>
      <webElementGuid>bbe3906c-8d6b-496d-b578-d3b30b5103ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_open_invoices']/thead/tr/th[6]</value>
      <webElementGuid>c9060e03-86c2-40f4-98d7-dc0930315046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[2]/following::th[1]</value>
      <webElementGuid>81b68035-d7a6-4b2b-aeff-7f22177da557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Date'])[2]/following::th[2]</value>
      <webElementGuid>8f39ff38-8000-4aca-9b14-569c70fad64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Approval'])[1]/preceding::th[1]</value>
      <webElementGuid>92672b01-a92b-4362-bf1a-152997af877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::th[2]</value>
      <webElementGuid>165638a1-a0aa-4abd-ac3a-58ab4b0fd379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/table/thead/tr/th[6]</value>
      <webElementGuid>a45b448f-5627-4a92-b76b-71853e83c499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Amount' or . = 'Amount')]</value>
      <webElementGuid>c0f31b8f-36bc-4d22-aab1-d4fbc9cb045d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
