<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Current-Approval</name>
   <tag></tag>
   <elementGuidId>7f371fa5-3588-4fa9-802f-e661495ed2d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table_open_invoices']/thead/tr/th[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Current Approval: activate to sort column ascending&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>0be8a761-97fc-48e8-8c6a-a9c832751046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center w-50% sorting</value>
      <webElementGuid>41a17142-f609-4ace-8e4e-4ab8031a658d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fb4d2286-4011-4367-aa74-9ea76b09ac74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table_open_invoices</value>
      <webElementGuid>47bf2e19-1b64-4d26-a0c3-789f0e90011e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>782fa16a-cfd0-45f1-a32a-ab0a1cb03d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>168e0592-474a-4b5c-b0a2-4a5b82e46535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Current Approval: activate to sort column ascending</value>
      <webElementGuid>14ccc9a6-8c79-4dcc-88f0-3fca670a8ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Current Approval</value>
      <webElementGuid>32dcbb4c-51a0-4137-b697-fca09c1cad84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_open_invoices&quot;)/thead[@class=&quot;table-light&quot;]/tr[1]/th[@class=&quot;text-center w-50% sorting&quot;]</value>
      <webElementGuid>128bbb9f-9608-433c-84c7-ea2896bb12e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_open_invoices']/thead/tr/th[7]</value>
      <webElementGuid>c630b8db-8674-40f9-8e77-9e207356c6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[2]/following::th[1]</value>
      <webElementGuid>bf5004d1-b0b0-416c-9ca7-ea031af549d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Name'])[2]/following::th[2]</value>
      <webElementGuid>c048fddb-f070-4612-91d0-90a90841cc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::th[1]</value>
      <webElementGuid>53a9061f-45fb-4109-9905-34c36b70c86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/preceding::th[2]</value>
      <webElementGuid>a5023f53-da4e-4e35-9067-ce5e55fbbca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Current Approval']/parent::*</value>
      <webElementGuid>e2acb01d-5009-45d5-a5c3-4c2dda838799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/table/thead/tr/th[7]</value>
      <webElementGuid>b9a44e84-7ee3-4363-876b-15175ec59484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Current Approval' or . = 'Current Approval')]</value>
      <webElementGuid>d15319ab-eb8e-4cf9-bde3-f7f82c8db5c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
